services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: events_db
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  db_data: