"""add event registration table.

Revision ID: 988d9eb2eadf
Revises: e297e2d5fd67
Create Date: 2025-06-12 14:38:02.262995.

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '988d9eb2eadf'
down_revision: Union[str, None] = 'e297e2d5fd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
