"""add speakers

Revision ID: 0236752b45c1
Revises: 14c2b28e54d0
Create Date: 2025-06-13 10:07:23.009869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0236752b45c1'
down_revision: Union[str, None] = '14c2b28e54d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('speaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['speaker_id'], ['id'])
    op.add_column('user', sa.Column('is_speaker', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_speaker')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'speaker_id')
    # ### end Alembic commands ###
